# Generated by Django 3.0.5 on 2020-04-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'servicio', 'verbose_name_plural': 'servicios'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='created',
        ),
        migrations.RemoveField(
            model_name='service',
            name='update',
        ),
    ]
