# Generated by Django 3.0.5 on 2020-04-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200424_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de edición'),
        ),
    ]
