# Generated by Django 3.0.5 on 2020-04-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created'], 'verbose_name': 'servicio', 'verbose_name_plural': 'servicios'},
        ),
        migrations.AddField(
            model_name='service',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de creación'),
        ),
    ]
